# Generated by Django 5.1.1 on 2024-10-02 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialdata',
            name='period',
            field=models.CharField(choices=[('annual', 'Annual'), ('quarterly', 'Quarterly')], default='annual', max_length=20),
        ),
    ]
