# Generated by Django 5.1.1 on 2024-10-02 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_financialdata_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialdata',
            name='value',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
    ]
